name: jett
services:
  airflow:
    image: airflow-standalone-local-jett
    container_name: airflow-jett-dev
    build:
      context: ..
      dockerfile: ./.container/Dockerfile
      args:
        AIRFLOW_VERSION: ${AIRFLOW_VERSION:-2.9.2}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.10}
        SPARK_VERSION: ${SPARK_VERSION:-3.4.1}
    ports:
      - "8081:8080"
    command: [ "airflow", "standalone" ]
    environment:
      AIRFLOW_HOME: "/opt/airflow"
      PYTHONPATH: "/opt/airflow/:/opt/airflow/plugins/"
      AIRFLOW_CONFIG: "/opt/airflow/airflow.cfg"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
      - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
      - ${AIRFLOW_PROJ_DIR:-.}/.container/airflow.standalone.cfg:/opt/airflow/airflow.cfg
      # NOTE: Mount tool package suppose as it use GitSync on production instead
      #   of install via Python package.
      - ${AIRFLOW_PROJ_DIR:-.}/jett:/opt/airflow/plugins/jett
